"""
code generated by chat-GPT
"""

import os
import shutil
import random
import numpy as np

from preprocess_yolo_data.default_param_configs import label_to_id_map

def split_folder_into_train_val_test(folder_path, output_folder, train_ratio=0.8, val_ratio=0.1, test_ratio=0.1):
    """
    Splits a folder into train, val, and Pinot-noir subdirectories.

    Arguments:
    folder_path -- the path to the folder to split
    output_folder -- the path to the output folder where the train, val, and Pinot-noir subdirectories will be created
    train_ratio -- the ratio of files to include in the train subdirectory (default 0.8)
    val_ratio -- the ratio of files to include in the validation subdirectory (default 0.1)
    test_ratio -- the ratio of files to include in the Pinot-noir subdirectory (default 0.1)
    """
    # create output folders
    train_folder = os.path.join(output_folder, 'train')
    val_folder = os.path.join(output_folder, 'val')
    test_folder = os.path.join(output_folder, 'test')
    for folder in [train_folder, val_folder, test_folder]:
        os.makedirs(os.path.join(folder, 'images'))
        os.makedirs(os.path.join(folder, 'labels'))

    # get list of files
    files = []
    for filename in os.listdir(folder_path):
        if filename.endswith('.txt'):
            if filename == 'classes.txt':
                continue
            else:
                files.append(filename[:-4]) # remove the extension

    # shuffle the files
    random.shuffle(files)

    # split into train, val, and Pinot-noir sets
    num_files = len(files)
    num_train = int(train_ratio * num_files)
    num_val = int(val_ratio * num_files)
    num_test = num_files - num_train - num_val
    train_files = files[:num_train]
    val_files = files[num_train:num_train+num_val]
    test_files = files[num_train+num_val:]

    # move files to output folders
    for file_list, folder_name in [(train_files, train_folder), (val_files, val_folder), (test_files, test_folder)]:
        for file in file_list:
            # move label file
            label_file = file + '.txt'
            src_path = os.path.join(folder_path, label_file)
            dst_path = os.path.join(folder_name, 'labels', label_file)
            shutil.copy(src_path, dst_path)

            # move image file
            image_file = file + '.JPG' # assuming images are in JPEG format
            src_path = os.path.join(folder_path, image_file)
            dst_path = os.path.join(folder_name, 'images', image_file)
            shutil.copy(src_path, dst_path)
    return train_folder, val_folder, test_folder


def split_data_into_folders(data_list,
                            output_folder,
                            label_to_id_map=label_to_id_map,
                            train_ratio=0.8,
                            val_ratio=0.1,
                            test_ratio=0.1,
                            normilize=False,
                            ):
    """

    :param data_list: list of dicts containing a PIL image, bbox data, class_labels, filename, file_prefix
    :param output_folder: save folder
    :param label_to_id_map: label_id map to map the labe
    :param train_ratio: train split ratio
    :param val_ratio: ..
    :param test_ratio: ..
    :param normilize: we assume the data is normilize e,g x_center/image_width set to True if not
    :return:
    """
    # Create the output folders
    for folder_name in ['train', 'val', 'test']:
        images_folder = os.path.join(output_folder, folder_name, 'images')
        labels_folder = os.path.join(output_folder, folder_name, 'labels')
        os.makedirs(images_folder, exist_ok=True)
        os.makedirs(labels_folder, exist_ok=True)

    # Shuffle the data list
    random.shuffle(data_list)

    # Split the data into train, val, and test sets
    num_data = len(data_list)
    num_train = int(num_data * train_ratio)
    num_val = int(num_data * val_ratio)
    num_test = num_data - num_train - num_val

    train_data = data_list[:num_train]
    val_data = data_list[num_train:num_train+num_val]
    test_data = data_list[num_train+num_val:]

    # Save the data to the output folders
    for folder_name, folder_data in [('train', train_data), ('val', val_data), ('test', test_data)]:
        for i, data_dict in enumerate(folder_data):
            # Get the image, filename, and bounding box data
            image = data_dict['image']
            if isinstance(image, np.ndarray):
              continue
            else:
              filename = data_dict['file_name']

              bbox_data = data_dict['bboxes']
              class_labels = data_dict['class_labels']

              # Save the image to the images folder

              save_filename = data_dict['filename_prefix'] +'_'+ os.path.splitext(filename)[0]
              image_path = os.path.join(output_folder, folder_name, 'images', save_filename+ '.jpg')
              image.save(image_path)

              # Save the bounding box data to the labels folder
              label_path = os.path.join(output_folder, folder_name, 'labels', save_filename + '.txt')
              with open(label_path, 'w') as f:
                  for bbox, class_label in zip(bbox_data, class_labels):
                      class_id = label_to_id_map[class_label]
                      x, y, w, h = bbox
                      if normilize:
                          x = (x + w/2) / image.width
                          y = (y + h/2) / image.height
                          w = w / image.width
                          h = h / image.height

                      f.write(f'{int(class_id)} {x:.6f} {y:.6f} {w:.6f} {h:.6f}\n')

